### ISSUE TITLE
March 12th MVP Checklist

### ISSUE THREAD

**Issue by seveibar** [tscircuit/tscircuit#1]
- [x] "My Packages" on homepage should load the user's packages
- [x] Changelog should load on homepage
- [x] Changelog should load all contributions (bug)
- [x] CLI should have `tsci publish`
- [x] CLI should allow for locking a release
- [x] Package page should load previews with package
- [x] Package page should show example code snippet of shown example
- [x] `tsci dev` should load a development window for examples
- [x] Homepage should link to registry
- [x] Registry should be deployed
- [x] `tscircuit` package should have everything you need and update nightly
