### ISSUE TITLE
March 12th MVP Checklist

### ISSUE THREAD

**Issue by seveibar** [tscircuit/tscircuit#2]
- [ ] "My Packages" on homepage should load the user's packages
- [ ] Changelog should load on homepage
- [ ] Changelog should load all contributions (bug)
- [ ] CLI should have `tsci publish`
- [ ] CLI should allow for locking a release
- [ ] Package page should load previews with package
- [ ] Package page should show example code snippet of shown example
- [ ] `tsci dev` should load a development window for examples
- [ ] Homepage should link to registry
- [ ] Registry should be deployed
