### ISSUE TITLE
"Ordered Trace Autorouting" Roadmap

### ISSUE THREAD

**Issue by seveibar** [tscircuit/tscircuit#436]
"Ordered Trace Autorouting" is a deterministic method of autorouting where each trace has an "order_index" indicating when it gets to autoroute. This allows preferential treatment of traces and can simplify understanding the autorouter, because a timed view  of autorouting can be viewed by inspecting the autoroute at different points

This is an unconventional way to autoroute because in "ordered trace autorouting" you can't really use "rip and replace" techniques.

The advantage of ordered trace autorouting is in it's high level of determinism. When working on a project where traces need frequent review, it may be better to have hints and ordered traces.

---

- [ ] Add `autoroute_order_index` to `pcb_route`
- [ ] Support filtering or making transparent traces of a higher order index (to allow seeing the autorouting over time)
- [ ] Support "manual reordering" where you can change the order of the trace from the pcb viewer
