### ISSUE TITLE
Issue List 09/21/2024

### ISSUE THREAD

**Issue by seveibar** [tscircuit/tscircuit#448]
These are issues I found when trying to work with tscircuit this morning:

- [ ] Could not fully route the macrokeypad in the cli repo
   - [ ] Sometimes unnecessarily long/complicated routes are created- why aren't these automatically simplified? Need to see incremental autorouting to get a good test
   - [ ] In the screenshot below, this trace is super overrouted, why have 3 routes go to the same hole with a mess of vias along the way? The nearest-neighbor goal selection should have fixed this

<img width="1357" alt="Screenshot 2024-09-21 at 8 47 30 AM" src="https://github.com/user-attachments/assets/e540630a-7dda-4b50-b95e-8e8ffe0f8706">

- [x] #452
- [x] #451
- [x] [Kicad Converter doesn't create edge cuts/board outline layer](https://github.com/tscircuit/kicad-converter/issues/9)
- [x] [Kicad Converter doesn't have nets, so DRC checks don't work](https://github.com/tscircuit/kicad-converter/issues/8)

![image](https://github.com/user-attachments/assets/3c6fea8c-5011-4fd9-8ca8-3ab262be03bb)

- [ ] Vias aren't highlighted when hovering over net in pcb viewer, you also can't hover over vias to highlight the net they're connected to

![image](https://github.com/user-attachments/assets/4d3461e8-3f85-441f-824c-19e3065fcc7e)

- [ ] Schematic viewer is not drawing chips (issue from migration to tscircuit core)

![image](https://github.com/user-attachments/assets/1eb837b8-4304-41b2-88f2-b362b4e1ef8c)

- [ ] Want to import kicad modules and footprints easily 
- [ ] Want a pico2 module to drop into the macrokeypad

**Comment by seveibar** [comment]
Some notes from the end of the day:

- [ ] We should make it easier to use 3d models, it's currently really difficult to even import 3d models. Ideally you can just specify the path to a 3d model that you have in your source code, then ideally we figure out how to make that work without bundling it inside the circuit json
- [ ] STEP files can't be loaded in and that's annoying. There is no easy solution here but i've created an issue #449 to maybe have a proxy handle it
