### ISSUE TITLE
March 19th Checklist

### ISSUE THREAD

**Issue by seveibar** [tscircuit/tscircuit#6]
- [ ] Move registry to homepage
- [ ] Landing page with installation instructions
- [ ] Landing page video tutorial
- [ ] Getting Started Tutorial
- [x] #20
- [ ] Soup zod and docs
- [x] Accept footprint functions/elements
- [x] Footprint builder function improvements
- [ ] Improve allowed footprint string names
- [x] Footprint registry/generator/package `@tscircuit/footprints`
- [ ] Introduce camel case parallels to react-fiber
- [x] Errors should propagate to dev server
- [ ] Schematic router should be smarter
- [ ] Handle netalias PCB routing - allow for ports/nearest connection for VCC etc.
- [ ] Board Outlines
- [ ] Documentation on how to build a layout system
- [ ] FTDI Basic 3v3
- [ ] Arduino Nano
- [ ] Stackblitz online playground
- [ ] SQL for Circuits
- [x] Preview should update even when window is not in focus for `tsci dev`
- [ ] Custom design schematic components (manual box definitions, line definitions etc. that are the correct size)

**Comment by warengonzaga** [comment]
I see, so no Arduino support for now?

**Comment by seveibar** [comment]
@warengonzaga coming very soon!
